### ISSUE TITLE
Unable to build and use

### ISSUE THREAD

**Issue by harisankarsadasivan** [haowenz/sigmap#8]
make CC=gcc-8 CXX=gcc-8
does not seem to build on gcc-8, 8.4.0, ubuntu 18.04
Error while building objs/sigmap.o: undefined reference to __cxa_pure_virtual.
collect2: error: ld returned 1 exit status.

If you have a different set of requirements for any binaries, please provide the links.

gcc-8 is installed from the second answer [here](https://askubuntu.com/questions/1028601/install-gcc-8-only-on-ubuntu-18-04).
The log shows the compiler invoked is gcc-8.

**Comment by harisankarsadasivan** [comment]
@haowenz Thanks for your recommendation.
I can confirm this works with gcc 9.1.0. The v8 I tried did not help. Maybe you want to change the project requirements accordingly.

**Comment by haowenz** [comment]
Thanks for you feedback. I will change the document accordingly.
